export default {
  montserrat: {
    black: "Montserrat-Black",
    blackItalic: "Montserrat-BlackItalic",
    bold: "Montserrat-Bold",
    boldItalic: "Montserrat-BoldItalic",
    extraBold: "Montserrat-ExtraBold",
    extraBoldItalic: "Montserrat-ExtraBoldItalic",
    extraLight: "Montserrat-ExtraLight",
    extraLightItalic: "Montserrat-ExtraLightItalic",
    italic: "Montserrat-Italic",
    light: "Montserrat-Light",
    lightItalic: "Montserrat-LightItalic",
    medium: "Montserrat-Medium",
    mediumItalic: "Montserrat-MediumItalic",
    regular: "Montserrat-Regular",
    semiBold: "Montserrat-SemiBold",
    semiBoldItalic: "Montserrat-SemiBoldItalic",
    thin: "Montserrat-Thin",
    thinItalic: "Montserrat-ThinItalic",
  },
  sfPro: {
    black: "SFProDisplay-Black",
    blackItalic: "SFProDisplay-BlackItalic",
    bold: "SFProDisplay-Bold",
    boldItalic: "SFProDisplay-BoldItalic",
    extraBold: "SFProDisplay-ExtraBold",
    extraBoldItalic: "SFProDisplay-ExtraBoldItalic",
    extraLight: "SFProDisplay-ExtraLight",
    extraLightItalic: "SFProDisplay-ExtraLightItalic",
    italic: "SFProDisplay-Italic",
    light: "SFProDisplay-Light",
    lightItalic: "SFProDisplay-LightItalic",
    medium: "SFProDisplay-Medium",
    mediumItalic: "SFProDisplay-MediumItalic",
    regular: "SFProDisplay-Regular",
    semiBold: "SFProDisplay-SemiBold",
    semiBoldItalic: "SFProDisplay-SemiBoldItalic",
    thin: "SFProDisplay-Thin",
    thinItalic: "SFProDisplay-ThinItalic",
  },
};
